### Send POST request with json body
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "swucs2",
  "password": "1234abc"
}

### Send POST request with json body
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "swucs2",
  "password": "1234abc"
}


### Send POST request with json body
POST http://localhost:3000/auth/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN3dWNzMiIsImlhdCI6MTcwNDA3MTUyMSwiZXhwIjoxNzA0MDc1MTIxfQ.QugF4qtfD7DG_Fac6ZOjI3QiEYUSIrPQbWtXS7CMgE0
